// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:moviez_app/infrastructure/home/dtos/movies_data_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MovieDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MovieDtoAdapter());
  }
}
